FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip podman sudo fuse-overlayfs && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN chmod 1777 /tmp

CMD ["python3"]